# Generated by Django 6.0.3 on 2026-03-24 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_remove_carro_nombre_carro_descripcion_carro_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('pse', 'PSE (Simulado)')], default='efectivo', max_length=20)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='carros.carro')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
