# Generated by Django 6.0.3 on 2026-04-29 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_features_avanzadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='carro',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('van', 'Van'), ('deportivo', 'Deportivo')], max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='ciudad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carro',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='carro',
            name='combustible',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico'), ('gas', 'Gas')], max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carro',
            name='estado',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno'), ('regular', 'Regular')], max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carro',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, help_text='km', null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carro',
            name='transmision',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='carro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pse', 'PSE (Simulado)'), ('tarjeta', 'Tarjeta de Crédito (Simulado)'), ('financiado', 'Financiamiento (Simulado)')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='CarroImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carros/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='carros.carro')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=1000)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='carros.carro')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='carros.carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'carro')},
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_dadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('autor', 'vendedor')},
            },
        ),
    ]
