# Generated by Django 5.2.4 on 2026-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_carro_options_carro_anio_carro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
