# Generated by Django 5.2.4 on 2026-05-11 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_alter_etiqueta_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
