# Generated by Django 5.2.4 on 2026-05-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_propietario_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='carros.carro'),
        ),
    ]
