# Generated by Django 5.2.4 on 2026-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_compra_carro_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
