# Generated by Django 5.2.4 on 2026-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_carro_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='Referencia generada por el procesador de pago', max_length=60),
        ),
    ]
